# Begin Project
project:
  type: tutorial-template
  # FYI: the tutorial-template project type is defined in the lmu-osc/tutorial-template extension
# End Project

# Begin Website
repo-url: https://github.com/lmu-osc/data-documentation-validation-R
website:
  title: "Data Documentation and Validation using R"
  page-footer:
    border: false
    center: © 2025 Reema Gupta, Malika Ihle. Published by LMU Open Science Center. Licensed under CC BY-SA 4.0.
  repo-url: https://github.com/lmu-osc/data-documentation-validation-R

  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/lmu-osc/data-documentation-validation-R
          - text: Report a Bug
            href: https://github.com/lmu-osc/data-documentation-validation-R/issues
      - icon: house-heart
        url: https://www.osc.lmu.de/

  sidebar:
    style: "docked"
    contents:
      - text: "Overview"
        href: index.qmd
      - section: "Tutorial Setup"
        href: tutorial-setup/index.qmd
        contents:
          - href: tutorial-setup/page-one.qmd
            text: "Project Setup"
          - href: tutorial-setup/page-two.qmd
            text: "Example Data & Tools"
      - section: "Data Dictionaries"
        href: data-dictionaries/index.qmd
        contents:
          - href: data-dictionaries/page-one.qmd
            text: "Concepts & Manual Creation"
          - href: data-dictionaries/page-two.qmd
            text: "Automated Creation with R"
      - section: "Data Validation"
        href: data-validation/index.qmd
        contents:
          - href: data-validation/page-one.qmd
            text: "Data Quality Concepts"
          - href: data-validation/page-two.qmd
            text: "Summary Statistics"
# End Website

# Begin Includes
include-in-header:
  - file: matomo-analytics.html
# End Includes

# Begin Format
# use only if needed. the default format for `tutorial-template` projects is tutorial-template-html+tutorial
# we recommend just extending the definition below if you need to make format changes
format:
  tutorial-template-html+tutorial:
    css:
      - footer/footer-style.css
    include-after-body:
      - file: footer/footer.html
# End Format

# Begin Editor
editor: source
# End Editor

bibliography: references.bib
