---
title: "About"
date: 2025-11-02
citation:
  type: "webpage"
  title: "Data Documentation and Validation using R Tutorial"
  container-title: "LMU Open Science Center"
  url: https://lmu-osc.github.io/data-dictionary-R/
  doi: "DOI HERE"
author:
  - name: Reema Gupta
    roles: [conceptualization, methodology, software, writing - original draft, writing - editing & review]
    degrees:
      - M.Sc.
    affiliation:
      - id: osc
        name: LMU Open Science Center
        ror: https://ror.org/05591te55
        isni: 000000041936973X
    orcid: 0000-0003-4509-6969
  - name: Malika Ihle
    roles: [conceptualization, methodology, supervision, writing - editing & review]
    degrees:
      - M.Sc.
      - PhD
    affiliation:
      - id: osc
        name: LMU Open Science Center
        ror: https://ror.org/05591te55
        isni: 000000041936973X
    orcid: 0000-0002-3242-5981
google-scholar: true
---


# Contributors

This site was authored by Reema Gupta and Malika Ihle.

# Licenses

The overall project is available under the **[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)** license found at [LICENSE](LICENSE.md); all code without any narrative text is also (at your option) available under the **[CC0 1.0 Universal](https://creativecommons.org/publicdomain/zero/1.0/)** license found at [LICENSE-CODE](LICENSE-CODE.md).

Why two licenses? The CC BY-SA 4.0 license is for the content of the website, while the CC0 1.0 Universal license is for the code and configuration files. This is a common practice for websites that include code snippets and other content that may be reused in other projects, particularly because the CC BY-SA 4.0 license is not intended to be used with software.

# Notes

This tutorial was primarily written in 2025 using R 4.4+ with the {datawizard} package for automated data dictionary creation. Major changes to the {datawizard} package can be found at the [package's website](https://easystats.github.io/datawizard/) for the most up-to-date information, and to confirm that our tutorial is not out-of-date. 

